services:
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - db:/data/db
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    profiles:
      - donotstart
    depends_on:
      - mongo
  api:
    container_name: api
    build: ./KPIs-cache-system/
    ports:
      - 3005:3005
    env_file:
      - .env
    environment:
      - KPI_CACHE_PROD_MODE=true
      - DB_HOST=$MONGODB_HOST
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
    depends_on:
      - mongo
    stdin_open: true
    tty: true
  client:
    container_name: client
    build: .
    volumes:
      - client:/home/node/client
    stdin_open: true
    tty: true
  caddy:
    container_name: caddy
    image: caddy:2.8.4-alpine
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - client:/client
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - client
volumes:
  db:
  client:
  caddy_data:
  caddy_config: